### PR TITLE
Added Landing Page Photo for IskoXpress

### PR DESCRIPTION
**Pull request by lueezzzz**

### CODE REVIEW

**Review by jrolana — APPROVED** [review]

**Review by jrolana — APPROVED** [review]
pachange ng filename to lowercase and pachange lang din ng line 5 para malink ang image sa iskoxpress. thank youu!
image

**Comment by lueezzzz** [comment]
hello done na!

**Comment by jrolana** [comment]
nice thank you sm!! pa-merge na lang salamatt

**Comment by lueezzzz** [comment]
mergedd!

**Pull request merged**
